name: Update .pre-commit-config.yaml

on:
  schedule:
  - cron: '0 3 * * *'   # Every day at 03:00 UTC
  workflow_dispatch:

jobs:
  update-pre-commit-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3   # v6.0.0

    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548   # v6.1.0
      with:
        python-version: '3.14'
        cache: "pip"

    - name: Install pre-commit
      run: pip install --upgrade pre-commit

    - name: Set up Git user
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Update .pre-commit-config.yaml
      run: pre-commit autoupdate --freeze

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412   # v7.0.9
      with:
        commit-message: "chore(deps): Update .pre-commit-config.yaml"
        title: "chore(deps): Update .pre-commit-config.yaml"
        body: "Automated update of .pre-commit-config.yaml via scheduled workflow."
        branch: "update/pre-commit-config-yaml"
        base: ${{ github.ref_name }}
        labels: "update"
        reviewers: "linuxdaemon"
        assignees: "linuxdaemon"
        sign-commits: true
